import Foundation

/// Generates hook scripts and handles installation logic.
public enum HookInstaller {
    public static let hookNames = ["pre-commit", "pre-push"]

    /// The hook script that runs the project-hooks binary.
    ///
    /// The script tries `binaryPath`, then `~/.local/bin/project-hooks`, and accepts only absolute paths. It never
    /// looks inside the repository or on `PATH`: git does not run hooks that a repository ships, and a cloned
    /// repository must not be able to choose the program that these hooks run either.
    /// - Parameter binaryPath: The absolute path of the binary to try first, usually the binary that installs the hook.
    /// - Returns: The script's text, which ends with a newline.
    public static func hookScript(binaryPath: String? = nil) -> String {
        let candidates = [binaryPath.map(shellQuoted), #""$HOME/.local/bin/project-hooks""#].compactMap(\.self)
        let candidateLines = candidates.map { "  \($0)" }.joined(separator: " \\\n")

        return """
            #!/usr/bin/env bash
            # Generated by project-hooks.
            set -euo pipefail

            HOOK_NAME="$(basename "$0")"

            BIN=""
            for candidate in \\
            \(candidateLines); do
              if [[ "$candidate" == /* && -x "$candidate" ]]; then
                BIN="$candidate"
                break
              fi
            done

            if [[ -z "$BIN" ]]; then
              echo "[ERROR] project-hooks binary not found." >&2
              echo "[INFO] Install it at ~/.local/bin/project-hooks." >&2
              exit 1
            fi

            exec "$BIN" "$HOOK_NAME" "$@"

            """
    }

    /// Write hook scripts to a hooks directory.
    /// - Parameters:
    ///   - hooksDir: Path to the hooks directory (e.g. `.git/hooks` or `~/.git-templates/hooks`)
    ///   - binaryPath: Optional explicit path to the project-hooks binary to embed in the script
    /// - Returns: List of installed hook file paths.
    /// - Throws: Any `FileManager` error from creating the hooks directory or writing each script.
    public static func installHooks(
        to hooksDir: String,
        binaryPath: String? = nil,
    ) throws -> [String] {
        let fm = FileManager.default
        let script = hookScript(binaryPath: binaryPath)

        // Create hooks directory if needed
        if !fm.fileExists(atPath: hooksDir) {
            try fm.createDirectory(atPath: hooksDir, withIntermediateDirectories: true)
        }

        var installed: [String] = []
        for hook in hookNames {
            let hookPath = URL(fileURLWithPath: hooksDir).appendingPathComponent(hook).path
            try script.write(toFile: hookPath, atomically: true, encoding: .utf8)
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: hookPath)
            installed.append(hookPath)
        }

        return installed
    }

    private static func shellQuoted(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\\''"))'"
    }
}
